name: BathyFeatures
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - rasterio
  - gdal
  - contourpy
  - shapely
  - pyproj
  - numpy
  - pandas
  - xarray
  - netcdf4
  - tqdm
